@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "This is my second post",
  "bgColor": "#4aa1f3",
  "privacy": "Public",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dlft3yfad/image/upload/v1693943804/64f787f9688688a3d08efc3a",
  "feelings": "happy"
}
