@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET  {{baseUrl}}/{{urlPath}}/user/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET  {{baseUrl}}/{{urlPath}}/user/profile
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET  {{baseUrl}}/{{urlPath}}/user/profile/
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET  {{baseUrl}}/{{urlPath}}/user/profile/posts/Mehul/6535f226c1b43ae7c35b2978/290683133123
Content-Type: application/json
Accept: application/json
withCredentials: true
